server:
  port: 8805
spring:
  application:
    name: shopspringboot-pay-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:3333
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping_rocketmq?useUnicode=true&character=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: syq
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.my.shop.pojo
rocketmq:
  #nameserver（单机/集群）地址 + 端口
  name-server: 192.168.50.148:9876;192.168.50.149:9876
  producer:
    #生产者群组
    group: ShoppingProducerGroup